### ISSUE TITLE
Chromedriver needs updating

### ISSUE THREAD

**Issue by dragancla** [appium/appium-chromedriver#136]
Chrome released v76, this module needs updating

```
ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Unable to automate Chrome version because it is too old for this version of Chromedriver.
Chrome version on the device: Chrome/76.0.3809.89
Visit 'https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md' to troubleshoot the problem.
Failed to start Chromedriver session: A new session could not be created. Details: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.6 x86_64)
    at getErrorFromResponseBody (/node_modules/webdriver/build/utils.js:215:10)
    at Request._callback (/node_modules/webdriver/build/request.js:103:64)
    at Request.self.callback (/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
```

**Comment by KazuCocoa** [comment]
Thanks

Auto download feature is also available in appium@beta, btw.  => 
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md#automatic-discovery-of-compatible-chromedriver
