### ISSUE TITLE
Getting error when trying to install running OS X

### ISSUE THREAD

**Issue by plaetzchen** [appium/appium-chromedriver#15]
Hi,

I get the following errors when trying to install the npm package:

```
> appium-chromedriver@2.3.5 install /Users/philip.brechler/node_modules/appium-chromedriver
> node install-npm.js


/Users/philip.brechler/node_modules/appium-chromedriver/node_modules/appium-support/node_modules/bluebird/js/main/promisify.js:268
        throw new TypeError("fn must be a function\u000a\u000a    See http://goo.gl/916lJJ\u000a");
              ^
TypeError: fn must be a function

    See http://goo.gl/916lJJ

    at Function.Promise.promisify (/Users/philip.brechler/node_modules/appium-chromedriver/node_modules/appium-support/node_modules/bluebird/js/main/promisify.js:268:15)
    at Object.<anonymous> (lib/fs.js:41:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/philip.brechler/node_modules/appium-chromedriver/node_modules/appium-support/build/lib/tempdir.js:12:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/philip.brechler/node_modules/appium-chromedriver/node_modules/appium-support/build/index.js:11:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (lib/install.js:6:42)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/philip.brechler/node_modules/appium-chromedriver/install-npm.js:13:5
    at Object.oncomplete (fs.js:107:15)
npm ERR! appium-chromedriver@2.3.5 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@2.3.5 install script.
npm ERR! This is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 15.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "appium-chromedriver" "--chromedriver_version=2.16"
npm ERR! cwd /Users/philip.brechler
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/philip.brechler/npm-debug.log
npm ERR! not ok code 0
```

**Comment by chrisjaure** [comment]
Getting the same error on Linux.

**Comment by rkavalap** [comment]
Unable to repro this. Closing due to inactivity.
