### ISSUE TITLE
Installation via proxy

### ISSUE THREAD

**Issue by zpo** [appium/appium-chromedriver#33]
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip...
RequestError: Error: Invalid protocol: squid-cluster.prod.dak.polsatc:
    at new RequestError (/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback](/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/request/request.js:199:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.init (/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/request/request.js:472:17)
    at Request.RP$initInterceptor [as init](/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/request-promise/lib/rp.js:123:25)
    at new Request (/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/request/request.js:141:8)
    at request (/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/request/index.js:55:10)
    at Function.get (/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/request/index.js:63:12)
    at installForPlatform$ (lib/install.js:80:28)
    at tryCatch (/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next](/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/atms/nodejs/lib/node_modules/appium-chromedriver/node_modules/core-js/library/modules/es6.promise.js:104:47)

**Comment by imurchie** [comment]
What is the output of 

```
npm config get proxy
npm config get https-proxy
```

**Comment by espenaf** [comment]
I have the same problem behind our corporate firewall. Regular npm install works fine, but downloading the chromedriver from chromedriver.storage.googleapis.com fails.

I have tried setting the proxy via 
`npm config set proxy http://proxy.company.lan:3128`
`npm config set https-proxy http://proxy.company.lan:3128`

or with the install command 
`npm install appium-chromedriver https-proxy=http://proxy.company.lan:3128 --proxy=http://proxy.company.lan:3128`

and in the ~/.npmrc, but nothing works, still get the same error:

info Chromedriver Install Installing Chromedriver version '2.21' for platform 'linux' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_linux64 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip...
RequestError: Error: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com chromedriver.storage.googleapis.com:80
    at new RequestError (/home/espenaf/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/home/espenaf/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/home/espenaf/svn/node_modules/request/request.js:200:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/home/espenaf/node_modules/request/request.js:831:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:258:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at connectErrorNT (net.js:998:8)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by lnnp1910** [comment]
I'm facing the same issue. Any ideas? npm install -g appium under corp proxy fails chromedriver downloading.

**Comment by idxn** [comment]
I have looked into the code and found that the request-premise library the project used will use proxy only if there is an explicit declared in the code or there is a environment system variable in the os. I have added these 2 env vars as following and it resolves the issue.
http_proxy
https_proxy
Moreover,  I've noticed that the library doesn't take proxy and https-proxy set in npm config into account.

**Comment by rkavalap** [comment]
Issue currently tracked under main appium repo.
 https://github.com/appium/appium/issues/7296
