### ISSUE TITLE
Cannot install - Socket Hang Up [OSX 10.11.4]

### ISSUE THREAD

**Issue by jeremyeaton89** [appium/appium-chromedriver#34]
Once I had upgraded from OSX 10.11.3 to 10.11.4, I was first unable to install appium via npm, which pointed to this library, which I cannot install locally.

```
➜  tasker git:(112400479-add-categories) ✗ npm install appium-chromedriver                              

> appium-chromedriver@2.8.3 install /Users/jeremyeaton/projects/taskrabbit/tasker/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.21' for platform 'mac' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip...
RequestError: Error: socket hang up
    at new RequestError (/Users/jeremyeaton/projects/taskrabbit/tasker/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/Users/jeremyeaton/projects/taskrabbit/tasker/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/Users/jeremyeaton/projects/taskrabbit/tasker/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/jeremyeaton/projects/taskrabbit/tasker/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketOnEnd (_http_client.js:288:9)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
tasker@0.0.1 /Users/jeremyeaton/projects/taskrabbit/tasker
└── gulp@3.9.1  extraneous

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/jeremyeaton/.nvm/versions/node/v4.0.0/bin/node" "/Users/jeremyeaton/.nvm/versions/node/v4.0.0/bin/npm" "install" "appium-chromedriver"
npm ERR! node v4.0.0
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.8.3 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.8.3 install script 'node install-npm.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeremyeaton/projects/taskrabbit/tasker/npm-debug.log
```

**Comment by jeremyeaton89** [comment]
Upgraded node and i'm back in the game (i was at 4.0.0)
