### ISSUE TITLE
Trying to use a chromedriver binary at the path /Users/automation/.appium/node_modules/appium-device-farm/chromedriver/chromedriver_mac64_v124.0.6367.207, but it doesn't exist!

### ISSUE THREAD

**Issue by ilendemli** [appium/appium-chromedriver#398]
We get an error when running our automation on android because the chromedriver binary filename it is searching for exists with dashes in the name and not with underscores. Maybe replace occurrences of dashes with underscores here?

https://github.com/appium/appium-chromedriver/blob/f09915cef815096492a197865f55faa964d3fa5a/lib/storage-client/storage-client.js#L304

**Comment by AfLosada** [comment]
Same thing is happening to me. The log looks like this:
```
[10c248ac][Chromedriver@2e03] Error: Trying to use a chromedriver binary at the path <my-path>/.appium/node_modules/appium-device-farm/chromedriver/chromedriver_mac64_v134.0.6998.165, but it doesn't exist!
    at Chromedriver.initChromedriverPath (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:518:13)
    at Chromedriver.start (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:610:32)
    at AndroidUiautomator2Driver.setupNewChromedriver (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/helpers.js:766:3)
    at AndroidUiautomator2Driver.startChromedriverProxy (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:281:10)
    at AndroidUiautomator2Driver.switchContext (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:114:5)
    at AndroidUiautomator2Driver.setContext (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:69:3)
 Error: Trying to use a chromedriver binary at the path <my-path>/.appium/node_modules/appium-device-farm/chromedriver/chromedriver_mac64_v134.0.6998.165, but it doesn't exist!
    at Chromedriver.initChromedriverPath (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:518:13)
    at Chromedriver.start (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:610:32)
    at AndroidUiautomator2Driver.setupNewChromedriver (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/helpers.js:766:3)
    at AndroidUiautomator2Driver.startChromedriverProxy (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:281:10)
    at AndroidUiautomator2Driver.switchContext (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:114:5)
    at AndroidUiautomator2Driver.setContext (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:69:3)
[10c248ac][Chromedriver@2e03] Trying to use a chromedriver binary at the path <my-path>/.appium/node_modules/appium-device-farm/chromedriver/chromedriver_mac64_v134.0.6998.165, but it doesn't exist!
[10c248ac][AndroidUiautomator2Driver@e23f] Encountered internal error running command: Error: Trying to use a chromedriver binary at the path <my-path>/.appium/node_modules/appium-device-farm/chromedriver/chromedriver_mac64_v134.0.6998.165, but it doesn't exist!
    at Object.errorWithException (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/lib/logging.js:41:45)
    at Chromedriver.start (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:697:22)
    at AndroidUiautomator2Driver.setupNewChromedriver (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/helpers.js:766:3)
    at AndroidUiautomator2Driver.startChromedriverProxy (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:281:10)
    at AndroidUiautomator2Driver.switchContext (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:114:5)
    at AndroidUiautomator2Driver.setContext (<my-path>/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:69:3)
[10c248ac][device-farm-main] Intercepted response for session 10c248ac-42cf-4a3f-84df-52d48b2363ca with method setContext
{} 10c248ac-42cf-4a3f-84df-52d48b2363ca
[10c248ac][device-farm-main] Saving log entry for session 10c248ac-42cf-4a3f-84df-52d48b2363ca with eventId undefined
[10c248ac][device-farm-main] Successfully saved log entry for 10c248ac-42cf-4a3f-84df-52d48b2363ca, commandName: setContext
[10c248ac][HTTP] <-- POST /wd/hub/session/10c248ac-42cf-4a3f-84df-52d48b2363ca/context 500 401 ms - 930 
[HTTP] Request idempotency key: 0fe82c3e-0f2b-424d-99d9-45a5a1beeb3b
[HTTP] --> POST /wd/hub/session {"capabilities":{"firstMatch":[{"appium:appPackage":"com.example.showcaseandroid","appium:automationName":"uiautomator2","platformName":"ANDROID","se:name":"kotlin-selenium-drm-test"}]}}
[AppiumDriver@af33] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{"appium:appPackage":"com.example.showcaseandroid","appium:automationName":"uiautomator2","platformName":"ANDROID","se:name":"kotlin-selenium-drm-test"}],"alwaysMatch":{"appium:requestId":"931fb4bf-96ef-4781-9901-07ff296609d5"}}]
[device-farm-main] 📱 Plugin Args: {"deviceAvailabilityTimeoutMs":30000,"platform":"both","androidDeviceType":"real","iosDeviceType":"real","skipChromeDownload":false}
[AppiumDriver@af33] Plugins which can handle cmd 'createSession': device-farm
[AppiumDriver@af33] Plugin device-farm is now handling cmd 'createSession'
[device-farm-main] 📱 pluginArgs: {"platform":"both","iosDeviceType":"real","androidDeviceType":"real","skipChromeDownload":false,"maxSessions":8,"adbRemote":[],"emulators":[],"simulators":[],"deviceAvailabilityTimeoutMs":30000,"deviceAvailabilityQueryIntervalMs":10000,"sendNodeDevicesToHubIntervalMs":30000,"checkStaleDevicesIntervalMs":30000,"checkBlockedDevicesIntervalMs":30000,"newCommandTimeoutSec":60,"bindHostOrIp":"10.134.18.189","enableDashboard":false,"removeDevicesFromDatabaseBeforeRunningThePlugin":false,"remoteConnectionTimeout":60000,"liveStreaming":true,"wdaBundleId":"","preBuildWDAPath":""}
```
